[versions]
accompanistWebview = "0.36.0"
androidGradlePlugin = "8.13.0"
androidxCore = "1.17.0"
androidxLifecycle = "2.9.4"
androidxActivity = "1.11.0"
androidxComposeBom = "2025.09.00"
androidxComposeCompiler = "1.5.10"
androidxHilt = "1.3.0"
androidxNavigation = "2.9.4"
androidxRoom = "2.8.0"
androidxTest = "1.7.0"
androidxTestExt = "1.3.0"
androidxTestRunner = "1.7.0"
coilCompose = "3.3.0"
coilNetworkOkhttp = "3.3.0"
landscapistCoil = "2.6.0"
nanoid = "1.0.1"
okio = "3.16.0"
paletteKtx = "1.0.0"
profileinstaller = "1.4.1"
startupRuntime = "1.2.0"
unfurl = "2.2.0"
weaviateClient = "5.4.0"
constraintLayout="1.1.1"
chromeCustomTabs = "1.9.0"
coroutines = "1.10.2"
composeIcons = "1.1.1"
crux = "5.1.0"
essence = "0.13.0"
fonts = "1.9.1"
hilt = "2.57.1"
junit = "4.13.2"
kotlin = "2.2.20"
kapt = "2.2.20"
ksp = "2.2.20-2.0.3"
librariesBom = "26.68.0"
library = "4.2.0"
libraryNoOp = "4.2.0"
markdown-renderer = "0.37.0"
okhttp = "5.1.0"
paging = "3.3.6"
postgrest = "0.2.0"
readability4j = "1.0.8"
retrofit = "3.0.0"
robolectric = "4.8"
splashscreen = "1.0.1"
supabase = "3.2.3"
shadowsPlus = "1.0.4"

tartlet = "0.3.0"
timber = "5.0.1"
workManager = "2.10.4"
ktorversion = "3.3.0"
espressoCore = "3.7.0"
uiautomator = "2.3.0"
benchmarkMacroJunit4 = "1.2.0-beta01"
material3 = "1.4.0"
firebaseBom = "34.4.0"
nav3Core = "1.0.0-rc01"
lifecycleViewmodelNav3 = "2.10.0-rc01"
material3AdaptiveNav3 = "1.3.0-alpha03"
firebaseAuth = "22.3.1"
playServicesAuth = "21.0.0"

#constraintlayoutVersion = "2.1.4"

[libraries]
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanistWebview" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3"}
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui"}
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling"}
androidx-compose-ui-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "fonts"}
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHilt" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigation" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilNetworkOkhttp" }
constraint-layout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintLayout" }

androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }

androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version = "3.3.6" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidxRoom" }

androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4"}
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest"}
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview"}
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

compose-icons-cssgg = { module = "br.com.devsrsouza.compose.icons:css-gg", version.ref = "composeIcons" }

google-cloud-vertexai = { module = "com.google.cloud:google-cloud-vertexai" }
landscapist-coil = { module = "com.github.skydoves:landscapist-coil", version.ref = "landscapistCoil" }
nanoid = { module = "io.viascom.nanoid:nanoid", version.ref = "nanoid" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
unfurl = { module = "me.saket.unfurl:unfurl", version.ref = "unfurl" }
weaviate-client = { module = "io.weaviate:client", version.ref = "weaviateClient" }
google-cloud-bom = { module = "com.google.cloud:libraries-bom", version.ref = "librariesBom" }

androidx-work-runtime-ktx = { module = "androidx.work:work-runtime", version.ref = "workManager" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "workManager" }
androidx-work-multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "workManager" }

chromeCustomTabs = { module = "androidx.browser:browser", version.ref = "chromeCustomTabs" }

chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "library" }
chucker-no-op = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "libraryNoOp" }

crux = { module = "com.chimbori.crux:crux", version.ref = "crux" }
essence = { module = "io.github.cdimascio:essence", version.ref = "essence" }
readability4j = { module = "net.dankito.readability4j:readability4j", version.ref = "readability4j" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version = "1.3.0" }
androidx-hilt-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version = "1.3.0" }

hilt-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }

robolectric = { module = "org.robolectric:roboelectric", version.ref = "robolectric"}

retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
sandwich = { module = "com.github.skydoves:sandwich", version = "2.1.3" }
retrofit-sandwich = { module = "com.github.skydoves:sandwich-retrofit", version = "2.1.3" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }

tartlet = { module = "io.yumemi:tartlet", version.ref = "tartlet" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

supabase-postgrest = { module = "io.github.jan-tennert.supabase:postgrest-kt", version.ref = "supabase" }
supabase-realtime = { module = "io.github.jan-tennert.supabase:realtime-kt", version.ref = "supabase" }
supabase-gotrue = { module = "io.github.jan-tennert.supabase:auth-kt", version.ref = "supabase" }
#postgrest = { module = "io.supabase:postgrest-kt", version.ref = "postgrest" }
ktor = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorversion" }

shadows-plus = { module = "com.github.GIGAMOLE:ComposeShadowsPlus", version.ref = "shadowsPlus"}

markdown-renderer = { module = "com.mikepenz:multiplatform-markdown-renderer", version.ref = "markdown-renderer"}
markdown-renderer-m3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "markdown-renderer"}
markdown-renderer-coil3 = { module = "com.mikepenz:multiplatform-markdown-renderer-coil3", version.ref = "markdown-renderer"}
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-juni t4", version.ref = "benchmarkMacroJunit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
#androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayoutVersion" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-ai = { module = "com.google.firebase:firebase-ai" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
google-signin = { group = "com.google.android.gms", name = "play-services-auth", version = "21.0.0" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
androidx-material3-adaptive-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3AdaptiveNav3" }


[bundles]
#androidx-compose = ["androidx-compose-material3", "androidx-compose-ui", "androidx-compose-ui-tooling-preview",]
retrofit = ["retrofit-core", "retrofit-gson", "retrofit-sandwich"]
work = ["androidx-work-runtime-ktx", "androidx-work-multiprocess"]
#hilts = ["hilt-android", "hilt-android-compiler", "hilt-android-testing", "hilt-compiler", "hilt-gradle-plugin"]
#room = ["androidx-room-runtime", "androidx-room-ktx", "androidx-room-compiler"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kapt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
hilt-gradle = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
